### ISSUE TITLE
Community Manager: Documentation

### ISSUE THREAD

**Issue by kaustubhavarma** [tattle-made/Uli#300]
Description: We need to create guides for the team- 
1. Onboarding Guide: 
- [x] how to create accounts on Github, 
- [x] how to navigate the repository, 
- [x] how to create issues etc.
- [x] Practice exercises

2. Meet the Team Guide, broadly consisting of the following:  
 -[ ]Team profiles
 -[ ]"What can you talk to X about?" (i.e topics of interest of each member)
