### ISSUE TITLE
Create a Platform for Abuse Collection

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#467]
### Features : 

- [x] https://github.com/tattle-made/Uli/issues/413
- [x] https://github.com/tattle-made/Uli/issues/246
- [x] Testing the lexicon for tagging slur words with partner organizations
- [x] https://github.com/tattle-made/Uli/issues/463
- [ ] https://github.com/tattle-made/Uli/issues/455
- [ ] https://github.com/tattle-made/Operations/issues/196
- [ ] #519
