### ISSUE TITLE
Clean up the Slur Dataset

### ISSUE THREAD

**Issue by kaustubhavarma** [tattle-made/Uli#578]
We need to clean up the slur dataset post the recent sync sessions that took place:

- [ ] Check similar slur lists
- [ ] Collect feedback on the useability of the slur list: is it useful as is, do we need root words? is metadata useful?
- [ ] Assessment: how to distill to root words.

**Comment by kaustubhavarma** [comment]
Reaching out to T&S teams to get feedback
